# Generated by Django 4.0.4 on 2022-05-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perg_resp', '0002_respostaprocini'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostaprocini',
            name='resposta',
            field=models.TextField(default=None),
        ),
    ]
