# Generated by Django 4.0.4 on 2022-05-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perg_resp', '0004_delete_respostaprocini'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processadoriniciante',
            name='alternativa_1',
        ),
        migrations.RemoveField(
            model_name='processadoriniciante',
            name='alternativa_2',
        ),
        migrations.RemoveField(
            model_name='processadoriniciante',
            name='alternativa_3',
        ),
        migrations.RemoveField(
            model_name='processadoriniciante',
            name='alternativa_4',
        ),
        migrations.RemoveField(
            model_name='processadoriniciante',
            name='pergunta',
        ),
        migrations.RemoveField(
            model_name='processadoriniciante',
            name='resposta',
        ),
        migrations.AddField(
            model_name='processadoriniciante',
            name='correto',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processadoriniciante',
            name='errado',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
